local _IlllIl=string.byte;local _IlllIIl=string.char;local _llIII=string.sub;local _IIlIIl=table.concat;local _IllIll=table.insert;local _IlIlIl=math.ldexp;local _IllIlI=getfenv or function()return _G end;local _IlIllI=setmetatable;local _IlIlll=select;local _IlIlIIl=unpack or table.unpack;local _lIllIl=tonumber;local function _llIIIl(_IlIlII,_IlIIll,_IIlIIIl)local _IlIIlI=_IlIlII[1];local _IlIIIl=_IlIlII[2];local _IlIIII=_IlIlII[3];return(function(...)local _lIlIll=1;local _lIlIlI={};local _lIlIII={};local _IlIlI=1;local _lIlIII={};for _IlIII=0,_IlIlI-1 do if _IlIII>=_IlIIII then _lIlIlI[_IlIII-_IlIIII]=_IlIlll(_IlIII+1,...);else _lIlIII[_IlIII]=_IlIlll(_IlIII+1,...);end end local _IlIlI=_IlIlI-_IlIIII+1 local _IlIlII;local _IlIIll;while true do _IlIlII=_IlIIlI[_lIlIll];_IlIIll=_IlIlII[1];if _IlIIll<=5 then if _IlIIll<=2 then if _IlIIll<=0 then do return _lIlIII[_IlIlII[2]]end elseif _IlIIll==1 then _lIlIII[_IlIlII[2]]=_IlIlII[3];else _lIlIII[_IlIlII[2]]=_IllIlI()[_IlIlII[3]];end elseif _IlIIll<=3 then local _IlIIll=_IlIlII[2];local _IlIlI=_lIlIII[_IlIlII[3]];_lIlIII[_IlIIll+1]=_IlIlI;_lIlIII[_IlIIll]=_IlIlI[_IlIlII[4]];elseif _IlIIll>4 then _lIlIII[_IlIlII[2]]=_IllIlI()[_IlIlII[3]];else _lIlIII[_IlIlII[2]]=_lIlIII[_IlIlII[3]][_IlIlII[4]];end elseif _IlIIll<=8 then if _IlIIll<=6 then if(_lIlIII[_IlIlII[2]]==_IlIlII[4])then _lIlIll=_lIlIll+1;else _lIlIll=_IlIlII[3];end elseif _IlIIll==7 then do return end else local _lIlIIlI=_IlIIlI[_lIlIll+2];local _lIlIII=(_lIlIIlI.b-1)*50;local _lIlIlI=_lIlIII[_IlIlII[2]];for _IlIII=1,_IlIlII[4]do _lIlIlI[_lIlIII+_IlIII]=_lIlIII[_IlIlII[3]+_IlIII];end end elseif _IlIIll<=10 then if _IlIIll>9 then local _IlIIll=_IlIlII[2];local _IlIlI=_lIlIII[_IlIlII[3]];_lIlIII[_IlIIll+1]=_IlIlI;_lIlIII[_IlIIll]=_IlIlI[_IlIlII[4]];else _lIlIII[_IlIlII[2]]=_lIlIII[_IlIlII[3]][_IlIlII[4]];end elseif _IlIIll==11 then local _IlIlI;_lIlIII[_IlIlII[2]]=_IlIlII[3];_lIlIll=_lIlIll+1;_IlIlII=_IlIIlI[_lIlIll];_lIlIII[_IlIlII[2]]=_IlIlII[3];_lIlIll=_lIlIll+1;_IlIlII=_IlIIlI[_lIlIll];_IlIlI=_IlIlII[2]_lIlIII[_IlIlI]=_lIlIII[_IlIlI];_lIlIll=_lIlIll+1;_IlIlII=_IlIIlI[_lIlIll];_lIlIII[_IlIlII[2]]=_lIlIII[_IlIlII[3]];_lIlIll=_lIlIll+1;_IlIlII=_IlIIlI[_lIlIll];_lIlIII[_IlIlII[2]]=_IlIlII[3];else do return end end _lIlIll=_lIlIll+1;end end);end return _llIIIl({{{10,0,9,9,3},{2,0,0,0,7},{6,0,2,0,11},{11,0,0,0,8},{5,0,12,0,2},{7,0,12,0,4},{11,0,5,0,4},{3,0,10,12,1},{8,0,0,0,6},{9,0,0,0,10},{4,0,0,12,5},{1,0,0,0,3}},{},{}},{},"IlllIllI")

local _G,getfenv,setfenv=_G,getfenv,setfenv;local getfenv=getfenv;local _lIlIl=_G.game;local _lIlllI=_G.game:GetService("RunService");local _lIllII=_G.game:GetService("Players");local _lIlllI=_lIllII.LocalPlayer;local _IIlIIl=_G.game:GetService("TeleportService");local _IIlIIl=_G.game:GetService("ReplicatedStorage");local _IllIl=_G.game:GetService("Chat");local _IlIIlI=_G.game:GetService("UserInputService");local _IlllII=_G.game:GetService("VirtualUser");local _lIlllIl=_G.game:GetService("Workspace");local _IlIIlll=_G.game:GetService("VirtualInputManager");local _IlIIlll=_G.game:GetService("TextChatService");local _lIlllIl=_lIlllI.Heartbeat;local a=getfenv().api or {};local _lIllIIl={connections={},elements={},ui={},antiSitActive=false,spinActive=false,multiToolActive=false,equippedTools={},isHoldingKey=false};local _lIllIIl=a:AddTab("extras");

(function()local b=_lIllIIl:AddLeftGroupbox("credits");b:AddLabel('script by: @daskepta',true)end)();(function()local b=_lIllIIl:AddRightGroupbox("update logs");b:AddLabel('update logs:\n[+] fixed trash talk\n[+] teleport to silent aim target\n[+] added fling all feature\nfind any bugs? dm me. have any suggestions? @daskepta on discord',true)end)();

(function()local c=_lIllIIl:AddLeftGroupbox("server");c:AddButton("vc unban",function()local d,e=pcall(function()_lIlIl:GetService("VoiceChatService"):joinVoice()end);a:Notify(d and"reconnected to vc"or("vc failed: "..tostring(e)),2)end);c:AddButton("rejoin server",function()local d,e=pcall(function()_IIlIIl:TeleportToPlaceInstance(_lIlIl.PlaceId,_lIlIl.JobId,_lIlllI)end);a:Notify(d and"rejoining server"or("failed: "..tostring(e)),2)end);c:AddButton("copy join link",function()local f=_lIlIl.PlaceId;local g=_lIlIl.JobId;local h=string.format("cloneref(game:GetService('TeleportService')):TeleportToPlaceInstance(%d, '%s', game.Players.LocalPlayer)",f,g);setclipboard(h);a:Notify("copied server join script",3)end)end)();

local _lIlllII=_lIllIIl:AddLeftGroupbox("misc");local _lIlllII=_lIlllII:AddToggle("god_block",{Text="god block",Default=true});table.insert(_lIllIIl.connections,_lIlllI.Heartbeat:Connect(function()if _lIlllII.Value then local i=_lIlllI.Character;if not i then return end;_lIlIl.ReplicatedStorage.MainEvent:FireServer("Block",true);local j=i:FindFirstChildOfClass("Humanoid");if j then for k,l in ipairs(j:GetPlayingAnimationTracks())do if l.Animation.AnimationId:match("2788354405")then l:Stop()end end end;local m=i:FindFirstChild("BodyEffects");if m and m:FindFirstChild("Block")then m.Block:Destroy()end end end));

local _IlIllI=false;local function _IlIllI()while _IlIllI do local i=_lIlIl.Players.LocalPlayer;local n=i.Character or i.CharacterAdded:Wait();local o=n:WaitForChild("HumanoidRootPart");local p=_lIlllIl:FindFirstChild("Ignored")and _lIlllIl.Ignored:FindFirstChild("Drop");if p then for k,q in pairs(p:GetChildren())do if q:IsA("Part")and q.Name=="MoneyDrop"then local r=(o.Position-q.Position).Magnitude;if r<=10 then local s=q:FindFirstChildOfClass("ClickDetector");if s then fireclickdetector(s)end end end end end;task.wait(0.2)end end;_lIlllII:AddToggle("cash_aura_toggle",{Text="cash aura",Default=true,Callback=function(t)_IlIllI=t;if t then task.spawn(_IlIllI)end end});if Toggles.cash_aura_toggle and Toggles.cash_aura_toggle.Value then _IlIllI=true;task.spawn(_IlIllI)end;

local _IlIlll;_lIlllII:AddToggle("anti_afk",{Text="anti afk",Default=true,Callback=function(t)if t then _IlIlll=_lIlllI.Idled:Connect(function()_IlllII:Button2Down(Vector2.new(0,0),_lIlllIl.CurrentCamera.CFrame);task.wait(1);_IlllII:Button2Up(Vector2.new(0,0),_lIlllIl.CurrentCamera.CFrame)end)else if _IlIlll then _IlIlll:Disconnect();_IlIlll=nil end end end});


local _loadstring = loadstring;
local _getfenv = getfenv;
local _setfenv = setfenv;

return function()
    local _env = _getfenv(1);
    _env.api = _getfenv().api;
    _env.autoStompShouldStop = false;
    return _env;
end
